Serler/Models/PaperViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Serler.Models
{
    public class PaperViewModel
    {
        public int PaperId { get; set; }
        public string PaperTitle { get; set; }
        public int Rating { get; set; }
        public string Author { get; set; }
        public string Date { get; set; }
        public string JournalName { get; set; }
        public string Publisher { get; set; }
        public string Category { get; set; }
        public string Methodology { get; set; }
        public string Practice { get; set; }
        public string OutcomeBeingTested { get; set; }
        public string ContextWho { get; set; }
        public string ContextWhat { get; set; }
        public string ContextWhere { get; set; }
        public string StudyResult { get; set; }
        public string ImplementationIntegrity { get; set; }
        public string ConfidenceRating { get; set; }
        public string ConfidenceRatingReason { get; set; }
        public string WhoRated { get; set; }
        public string ResearchLevel { get; set; }
        public string ResearchQuestion { get; set; }
        public string ResearchMethod { get; set; }
        public string ResearchMetrics { get; set; }
        public string ParticipantsNature { get; set; }
        public int NoOfPeopleRated { get; set; }
        public bool IsActive { get; set; }
        public bool IsAnalyzed { get; set; }
        public bool isRejected { get; set; }
    }

}

Serler/Controllers/PaperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Serler.Models;
using System.Data.SqlClient;
using Dapper;
using System.IO;
using Rotativa.Options;

namespace Serler.Controllers
{
    public class PaperController : Controller
    {
        //
        // GET: /Paper/
        [HttpGet]
        public ActionResult SubmitPaper()
        {
            return View(new PaperViewModel());
        }

        [HttpPost]
        public ActionResult SubmitPaper(PaperViewModel model)
        {
            var isCorrectInput = true;
            if (model.PaperTitle == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("PaperTitle", "The title is empty.");
            }

            if (model.Category == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("Category", "The category is empty.");
            }

            if (model.Author == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("Author", "The author is empty.");
            }

            if (model.Date == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("Date", "The Date is empty.");
            }

            if (model.JournalName == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("JournalName", "Journal Name is empty.");
            }

            if (ModelState.IsValid && isCorrectInput == true)
            {
                using (var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["Serler"].ConnectionString))
                {
                    var query = string.Format("insert into Paper (PaperTitle, Date, Author, JournalName, Category, Methodology, Practice, IsActive, isAnalyzed, isRejected)" 
                    + "values ('{0}', '{1}', '{2}', '{3}', '{4}', '{5}', '{6}', 0, 0, 0)", model.PaperTitle, model.Date, model.Author, model.JournalName, 
                    model.Category, model.Methodology, model.Practice);
                    conn.Open();
                    conn.Execute(query);
                }
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult QuickSubmit()
        {
            return View(new PaperViewModel());
        }

        [HttpPost]
        public ActionResult QuickSubmit(PaperViewModel model)
        {
            var isCorrectInput = true;
            if (model.PaperTitle == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("PaperTitle", "The title is empty.");
            }

            if (model.Category == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("Category", "The category is empty.");
            }

            if (model.JournalName == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("JournalName", "Name of journal is empty.");
            }

            if (model.Author == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("Author", "The author is empty.");
            }

            if (model.Date == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("Date", "The Date is empty.");
            }

            if (model.Publisher == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("Publisher", "Publisher is empty.");
            }

            if (model.OutcomeBeingTested == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("OutcomeBeingTested", "Outcome being tested is empty.");
            }


            if (model.ContextWho == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("ContextWho", "Study context of who is is empty.");
            }

            if (model.ContextWhat == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("ContextWhat", "Study context of what is is empty.");
            }

            if (model.ContextWhere == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("ContextWhere", "Study context of where is is empty.");
            }

            if (model.WhoRated == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("WhoRated", "Who rated is is empty.");
            }

            if (model.StudyResult == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("StudyResult", "Result of study is empty.");
            }

            if (model.ImplementationIntegrity == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("ImplementationIntegrity", "Implementation Integrity cannot be empty.");
            }

            if (model.ConfidenceRating == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("ConfidenceRating", "Confidence Rating cannot be empty");
            }

            if (model.ConfidenceRating == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("ConfidenceRatingReason", "Reason for Confidence Rating cannot be empty");
            }

            if (model.ResearchQuestion == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("ResearchQuestion", "Research Question cannot be empty");
            }

            if (model.ResearchMetrics == null)
            {
                isCorrectInput = false;
                ModelState.AddModelError("ResearchMetrics", "Research Metrics cannot be empty");
            }

            if (ModelState.IsValid && isCorrectInput == true)
            {
                using (var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["Serler"].ConnectionString))
                {
                    var query = string.Format("insert into Paper (PaperTitle, Date, Author, JournalName, Category, Publisher, Methodology, Practice, OutcomeBeingTested, ContextWho," 
                    + " ContextWhat, ContextWhere, StudyResult, ImplementationIntegrity, ConfidenceRating, ConfidenceRatingReason, WhoRated, ResearchQuestion, ResearchMethod,"
                    + " ResearchMetrics, ResearchLevel, ParticipantsNature, IsActive, isAnalyzed, isRejected) "
                    + "values ('{0}', '{1}','{2}', '{3}','{4}', '{5}','{6}', '{7}', '{8}','{9}', '{10}','{11}', '{12}','{13}', '{14}','{15}', '{16}', '{17}',"
                    + " '{18}', '{19}','{20}', '{21}', 1, 1, 0)", model.PaperTitle, model.Date, model.Author, model.JournalName, model.Category, model.Publisher, 
                    model.Methodology, model.Practice, model.OutcomeBeingTested, model.ContextWho, model.ContextWhat, model.ContextWhere, model.StudyResult,
                    model.ImplementationIntegrity, model.ConfidenceRating, model.ConfidenceRatingReason, model.WhoRated, model.ResearchQuestion, model.ResearchMethod,
                    model.ResearchMetrics, model.ResearchLevel, model.ParticipantsNature);
                    conn.Open();
                    conn.Execute(query);
                }
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        public ActionResult AdministratePaper()
        {
            return View();
        }

        public ActionResult EditPaper()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ViewPaper(int id, string submit)
        {
            using (var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["Serler"].ConnectionString))
            {
                var query = "select * from Paper where PaperId = @PaperId";
                conn.Open();
                var model = conn.Query<PaperViewModel>(query, new { PaperId = id }).FirstOrDefault();
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult ViewPaper(PaperViewModel model, string submit)
        {
            if (ModelState.IsValid)
            {
                using (var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["Serler"].ConnectionString))
                {
                    var query = "Select PaperTitle = @PaperTitle, Category = @Category, Date = @Date, Author = @Author, JournalName = @JournalName, Publisher = @Publisher, " 
                    + "Rating = @Rating, NoOfPeopleRated = @NoOfPeopleRated, Methodology = @Methodology, Practice = @Practice, OutcomeBeingTested = @OutcomeBeingTested,"
                    + "ContextWho = @ContextWho, ContextWhat = @ContextWhat, ContextWhere = @ContextWhere, StudyResult = @StudyResult,"
                    + "ImplementationIntegrity = @ImplementationIntegrity, ConfidenceRating = @ConfidenceRating, ConfidenceRatingReason = @ConfidenceRatingReason, "
                    + "WhoRated = @WhoRated, ResearchQuestion = @ResearchQuestion, ResearchMethod = @ResearchMethod, ResearchMetrics = @ResearchMetrics,"
                    + " ResearchLevel = @ResearchLevel, ParticipantsNature = @ParticipantsNature from Paper;";
                    conn.Open();
                    conn.Execute(query, new { PaperTitle = model.PaperTitle, Category = model.Category, Date = model.Date, Author = model.Author, JournalName = model.JournalName, 

Serler/Views/Paper/AdministratePaper.cshtml
@model Serler.Models.PaperViewModel
@{
    var db = Database.Open("Serler");
    var selectQueryString = "SELECT * FROM Paper ORDER BY PaperTitle";
}
<h2>Example Category</h2>
@foreach (var row in db.Query(selectQueryString))
{
    <div class="form-group">
        <div class="row">
            <div class="col-md-2">
                <a href="@Url.Action("EditPaper", "Paper", new { id = row.PaperId })"><span class="label label-danger">@row.PaperTitle</span></a>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Research category</label>
            </div>
            <div class="col-md-10">
                @row.Category
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Year of publication</label>
            </div>
            <div class="col-md-10">
                @row.Date
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Author</label>
            </div>
            <div class="col-md-10">
                @row.Author
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Methodology</label>
            </div>
            <div class="col-md-10">
                @row.Methodology
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Practice</label>
            </div>
            <div class="col-md-10">
                @row.Practice
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>JournalName</label>
            </div>
            <div class="col-md-10">
                @row.JournalName
            </div>
        </div>
    </div>
}

Serler/Views/Paper/Pagination.cshtml
@model List<Serler.Models.PaginationModel>

<nav>
    <ul class="pagination">
        @foreach (var page in Model)
        {
            if (page.IsEnable)
            {
                if (page.IsActive)
                {
                    <li class="active"><a href="@Url.Content(page.Url)">@page.DisplayLabel</a></li>
                }
                else
                {
                    <li><a href="@Url.Content(page.Url)">@page.DisplayLabel</a></li>
                }
            }
            else
            {
                <li class="disabled"><a href="@Url.Content(page.Url)">@page.DisplayLabel</a></li>
            }
        }
    </ul>
</nav>

Serler/Views/Paper/Search.cshtml
@model Serler.Models.PagedViewModel<Serler.Models.PaperViewModel>

@{
    ViewBag.Title = "Search";
}

<div class="row">
    <div class="col-md-2">
        <h2>Search</h2>
    </div>
    <div class="col-md-6 padding20">
        @{Html.RenderPartial("SearchBar", Model.SearchModel);}
    </div>    
</div>
@if (Model.TotalCount == 0)
{
    <div>
        >> There is no paper matched.
    </div>
}
else
{
    <div>
        >> Showing 
        @if(Model.TotalCount < 10)
        {<span>@Model.TotalCount</span>}
        else
        {<span>10</span>}
        results of @Model.TotalCount
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Date</th>
                <th>Publisher</th>
                <th>Rating</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Result)
            {
                <tr>
                    <th><a href="@Url.Action("ViewPaper", "Paper", new { id = item.PaperId })">@item.PaperTitle</a></th>
                    <th>@item.Author</th>
                    <th>@item.Date</th>
                    <th>@item.Publisher</th>
                    <th>@item.Rating</th>
                    <th>
                        <a type="button" class="btn btn-default" href="@Url.Action("EditPaper", "Paper", new { id = item.PaperId })"><i class="glyphicon glyphicon-edit"></i></a>
                    </th>
                </tr>
            }
        </tbody>
    </table>
    {Html.RenderPartial("Pagination", Model.PaginationModel);}
}

Serler/Views/Paper/SearchBar.cshtml
@model Serler.Models.SearchModel

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-4">
            @Html.DropDownListFor(m => m.Attribute, new List<SelectListItem> {
                new SelectListItem { Value = "PaperTitle" , Text = "Title" },
                new SelectListItem { Value = "Author" , Text = "Author" },
                new SelectListItem { Value = "Publisher" , Text = "Publisher" }
            }, new { @class = "form-control", type = "text", name="attribute" })
        </div>
        <div class="col-md-8">
            <div class="input-group">
                @Html.TextBoxFor(m => m.SearchText, new { @class="form-control", placeholder="Search for...", name="searchText" })
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </div>
    </div>
}

Serler/Views/Paper/ViewAnalystList.cshtml
@model Serler.Models.PaperViewModel
@{
    var db = Database.Open("Serler");
    var selectQueryString = "SELECT * FROM Paper where IsAnalyzed = 0 and IsActive = 1 ORDER BY PaperTitle";
}
@foreach (var row in db.Query(selectQueryString))
{
    <div class="form-group">
        <div class="row">
            <div class="col-md-2">
                <a href="@Url.Action("AnalyzePaper", "Paper", new { id = row.PaperId })"><span class="label label-danger">@row.PaperTitle</span></a>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Research category</label>
            </div>
            <div class="col-md-10">
                @row.Category
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Year of publication</label>
            </div>
            <div class="col-md-10">
                @row.Date
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Author</label>
            </div>
            <div class="col-md-10">
                @row.Author
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Methodology</label>
            </div>
            <div class="col-md-10">
                @row.Methodology
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Practice</label>
            </div>
            <div class="col-md-10">
                @row.PaperTitle
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Journal Name</label>
            </div>
            <div class="col-md-10">
                @row.JournalName
            </div>
        </div>
    </div>
}

Serler/Views/Paper/ViewModeratorList.cshtml
@model Serler.Models.PaperViewModel
@{
    var db = Database.Open("Serler");
    var selectQueryString = "SELECT * FROM Paper where IsActive = 0 and isRejected = 0 ORDER BY PaperTitle";
}
@foreach (var row in db.Query(selectQueryString))
{
    <div class="form-group">
        <div class="row">
            <div class="col-md-2">
                <a href="@Url.Action("ModeratePaper", "Paper", new { id = row.PaperId })"><span class="label label-danger">@row.PaperTitle</span></a>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Research category</label>
            </div>
            <div class="col-md-10">
                @row.Category
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Year of publication</label>
            </div>
            <div class="col-md-10">
                @row.Date
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Author</label>
            </div>
            <div class="col-md-10">
                @row.Author
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Methodology</label>
            </div>
            <div class="col-md-10">
                @row.Methodology
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Practice</label>
            </div>
            <div class="col-md-10">
                @row.Practice
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Journal Name</label>
            </div>
            <div class="col-md-10">
                @row.JournalName
            </div>
        </div>
    </div>
}

Serler/Views/Paper/ViewPaper.cshtml
@model Serler.Models.PaperViewModel

@{
    ViewBag.Title = "Paper's Details";
}

    <h2>Paper's details</h2>
    <br />
    @using (Html.BeginForm())
    {

        <div class="form-group">
            <div class="row">
                <div class="col-md-2">
                    <label>Paper Title</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.PaperTitle)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Author</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.Author)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Journal Name</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.JournalName)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Year of publication</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.Date)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Research category</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.Category)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Publisher</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.Publisher)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Methodology</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.Methodology)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Practice</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.Practice)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Outcome being tested</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.OutcomeBeingTested)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Study Context (who)</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ContextWho)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Study Context (what)</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ContextWhat)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Study Context (where)</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ContextWhere)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Result of Study</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.StudyResult)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Integrity of implementation</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ImplementationIntegrity)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Confidence Rating</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ConfidenceRating)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Confidence Rating Reason</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ConfidenceRatingReason)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Who rated</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.WhoRated)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Research Question</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ResearchQuestion)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Research Method</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ResearchMethod)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Research Metrics</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ResearchMetrics)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Research Level</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ResearchLevel)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Nature of Participants</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.ParticipantsNature)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Rating</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.Rating)
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    <label>Number Of people rated</label>
                </div>
                <div class="col-md-10">
                    @Html.DisplayFor(m => m.NoOfPeopleRated)
                </div>
            </div>
           </div>
    <div id="print-pdf" align="center">
        <a id="print-me" class="print-btn"
           href='@Url.Action("PrintMyView", "Paper",
             new { id = Model.PaperId,
                   title = Model.PaperTitle,
                   author = Model.Author,
                   journalName = Model.JournalName,
                   publisher = Model.Publisher,
                   category = Model.Category,
                   methodology = Model.Methodology,
                   practice = Model.Practice,
                   outcomeBeingTested = Model.OutcomeBeingTested,
                   contextWho = Model.ContextWho,
                   contextWhat = Model.ContextWhat,
                   contextWhere = Model.ContextWhere,
                   studyResult = Model.StudyResult,
                   implementationIntegrity = Model.ImplementationIntegrity,
                   confidenceRating = Model.ConfidenceRating,
                   confidenceRatingReason = Model.ConfidenceRatingReason,
                   whoRated = Model.WhoRated,
                   researchQuestion = Model.ResearchQuestion,
                   researchMethod = Model.ResearchMethod,
                   researchMetrics = Model.ResearchMetrics,
                   researchLevel = Model.ResearchLevel,
                   participantsNature = Model.ParticipantsNature,
                   ratin = Model.Rating,
                   noOfRated = Model.NoOfPeopleRated,
                   date = Model.Date }, null)'>Print Report</a>
    </div>
    }

Serler/Views/Paper/ViewPapers.cshtml
@{
    ViewBag.Title = "ViewPapers";
    var db = Database.Open("Serler");
    var selectQueryString = "SELECT * FROM Paper where IsActive = 1 and isAnalyzed = 1 and isRejected = 0 ORDER BY PaperTitle";
}

<h2>Example Category</h2>
@foreach (var row in db.Query(selectQueryString))
{
    <div class="form-group">
        <div class="row">
            <div class="col-md-2">
                <a href="@Url.Action("ViewPaper", "Paper", new { id = row.PaperId })"><span class="label label-danger">@row.PaperTitle</span></a>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Research category</label>
            </div>
            <div class="col-md-10">
                @row.Category
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Year of publication</label>
            </div>
            <div class="col-md-10">
                @row.Date
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Author</label>
            </div>
            <div class="col-md-10">
                @row.Author
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Methodology</label>
            </div>
            <div class="col-md-10">
                @row.Methodology
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Practice</label>
            </div>
            <div class="col-md-10">
                @row.Practice
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label>Journal Name</label>
            </div>
            <div class="col-md-10">
                @row.JournalName
            </div>
        </div>
    </div>
}